name: General Knowledge

on: [workflow_dispatch, push, pull_request]

jobs:

  general-knowledge:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        model:
          - meta-llama/llama-3.2-3b-instruct             # $0.0200/$0.0200 [ 128K]
          - mistralai/mistral-nemo                       # $0.0100/$0.0270 [ 128K]
          - google/gemma-3-4b-it                         # $0.0200/$0.0400 [ 128K]
          - microsoft/phi-4-multimodal-instruct          # $0.0500/$0.1000 [ 128K]
          - mistralai/ministral-8b                       # $0.1000/$0.1000 [ 128K]
          - ibm-granite/granite-4.0-h-micro              # $0.0170/$0.1100 [ 128K]
          - qwen/qwen3-8b                                # $0.0350/$0.1380 [ 128K]
          - amazon/nova-micro-v1                         # $0.0350/$0.1400 [ 128K]
          - openai/gpt-4.1-nano                          # $0.1000/$0.4000 [1000K]
          - google/gemini-2.5-flash-lite                 # $0.1000/$0.4000 [1000K]

    steps:
      - uses: actions/checkout@v4

      - run: ./chat-llm.js tests/en/canary-single-turn.txt
        env:
          LLM_API_BASE_URL: https://openrouter.ai/api/v1
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - run: ./chat-llm.js tests/en/general-knowledge.txt
        env:
          LLM_API_BASE_URL: https://openrouter.ai/api/v1
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}
