name: General Knowledge

on: [workflow_dispatch, push, pull_request]

jobs:

  general-knowledge:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        model:
          # FAIL:2- meta-llama/llama-3.2-3b-instruct             # $0.0100/$0.0200 [ 128K]
          - mistralai/mistral-nemo                       # $0.0100/$0.0270 [ 128K]
          - google/gemma-3n-e4b-it                       # $0.0200/$0.0400 [  32K]
          - google/gemma-3-4b-it                         # $0.0200/$0.0400 [ 128K]
          # FAIL:3 - mistralai/ministral-3b                       # $0.0400/$0.0400 [ 128K]
          - mistralai/mistral-7b-instruct-v0.3           # $0.0280/$0.0540 [  32K]
          - mistralai/mistral-small-3.2-24b-instruct     # $0.0500/$0.1000 [  32K]
          - google/gemma-3-12b-it                        # $0.0500/$0.1000 [ 128K]
          # FAIL:3 - microsoft/phi-3-mini-128k-instruct           # $0.1000/$0.1000 [ 128K]          
          - qwen/qwen3-8b                                # $0.0350/$0.1380 [ 128K]
          - amazon/nova-micro-v1                         # $0.0350/$0.1400 [ 128K]
          - microsoft/phi-4                              # $0.0700/$0.1400 [  16K]
          - google/gemini-flash-1.5-8b                   # $0.0380/$0.1500 [1000K]
          - amazon/nova-lite-v1                          # $0.0600/$0.2400 [ 300K]
          - qwen/qwen3-14b                               # $0.0800/$0.2400 [  40K]
          - mistralai/mixtral-8x7b-instruct              # $0.2400/$0.2400 [  32K]
          - meta-llama/llama-3.3-70b-instruct            # $0.0700/$0.2500 [ 128K]
          - qwen/qwen3-30b-a3b                           # $0.0800/$0.2900 [  40K]
          - google/gemini-2.0-flash-lite-001             # $0.0750/$0.3000 [1000K]
          - meta-llama/llama-4-scout                     # $0.0800/$0.3000 [ 320K]
          - google/gemini-2.0-flash-001                  # $0.1000/$0.4000 [1000K]
          - openai/gpt-4.1-nano                          # $0.1000/$0.4000 [1000K]
          - google/gemini-2.5-flash-lite-preview-06-17   # $0.1000/$0.4000 [1000K]

    steps:
      - uses: actions/checkout@v4

      - run: ./chat-llm.js tests/en/canary-single-turn.txt
        env:
          LLM_API_BASE_URL: https://openrouter.ai/api/v1
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - run: ./chat-llm.js tests/en/general-knowledge.txt
        env:
          LLM_API_BASE_URL: https://openrouter.ai/api/v1
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}
